from __future__ import annotations

import random

from app.config import Settings
from app.core.llm_json import OpenAIJsonClient
from app.models import BenchmarkCase, CreateIncidentRequest, IncidentSeverity, SyntheticGenerationRequest


class SyntheticIncidentGenerator:
    def __init__(self, settings: Settings) -> None:
        self.settings = settings
        self.llm_client = OpenAIJsonClient(settings)

    async def generate_cases(self, request: SyntheticGenerationRequest) -> list[BenchmarkCase]:
        if self.llm_client.is_available():
            try:
                return await self._generate_cases_with_llm(request)
            except Exception:
                return self._generate_cases_fallback(request)
        return self._generate_cases_fallback(request)

    async def generate_incidents(self, request: SyntheticGenerationRequest) -> list[CreateIncidentRequest]:
        cases = await self.generate_cases(request)
        return [
            CreateIncidentRequest(
                title=case.title,
                service=case.service,
                environment=case.environment,
                severity=case.severity,
                description=case.description,
                source=case.source,
                metrics=case.metrics,
                labels=case.tags,
                context={
                    "synthetic": True,
                    "expected_root_cause": case.expected_root_cause,
                    "expected_actions": case.expected_actions,
                    "difficulty": request.difficulty,
                },
            )
            for case in cases
        ]

    async def _generate_cases_with_llm(self, request: SyntheticGenerationRequest) -> list[BenchmarkCase]:
        services = request.services or ["checkout-api", "payments-api", "search-api", "orders-api", "billing-api"]
        payload = await self.llm_client.complete_json(
            model=self.settings.synthetic_generation_model or self.settings.openai_model,
            system_prompt=(
                "You generate realistic synthetic DevOps incident benchmark cases. "
                "Return JSON with a 'cases' list. Each case must have title, service, environment, severity, "
                "description, source, metrics, expected_root_cause, expected_actions, and tags. "
                "Mix noisy signals, false positives, incomplete evidence, and hard but realistic production incidents."
            ),
            user_prompt=(
                f"Generate {max(1, min(request.count, 12))} benchmark cases for services {services}. "
                f"Difficulty: {request.difficulty}. include_noise={request.include_noise}, "
                f"include_false_positives={request.include_false_positives}, "
                f"include_incomplete_evidence={request.include_incomplete_evidence}."
            ),
            temperature=0.7,
            usage_source="synthetic_generation",
        )
        raw_cases = payload.get("cases", [])
        parsed: list[BenchmarkCase] = []
        for item in raw_cases[: request.count]:
            severity_value = str(item.get("severity", "medium")).lower()
            severity = IncidentSeverity(severity_value) if severity_value in IncidentSeverity._value2member_map_ else IncidentSeverity.medium
            parsed.append(
                BenchmarkCase(
                    title=str(item.get("title", "Synthetic incident")),
                    service=str(item.get("service", random.choice(services))),
                    environment=str(item.get("environment", "production")),
                    severity=severity,
                    description=str(item.get("description", "Synthetic scenario generated by the model.")),
                    source=str(item.get("source", "synthetic")),
                    metrics={k: float(v) for k, v in dict(item.get("metrics", {})).items()},
                    expected_root_cause=str(item.get("expected_root_cause", "diagnostic review")),
                    expected_actions=[str(action) for action in item.get("expected_actions", [])],
                    tags=[str(tag) for tag in item.get("tags", [])],
                )
            )
        return parsed or self._generate_cases_fallback(request)

    def _generate_cases_fallback(self, request: SyntheticGenerationRequest) -> list[BenchmarkCase]:
        services = request.services or ["checkout-api", "payments-api", "search-api", "orders-api", "billing-api"]
        environments = ["production", "staging"]
        templates = [
            {
                "kind": "latency",
                "title": "{service} latency surge during peak traffic",
                "description": "p95 latency increased sharply and customer timeouts began during a traffic surge.",
                "severity": IncidentSeverity.high,
                "metrics": {"p95_latency_ms": 2400.0, "error_rate": 0.04},
                "root": "dependency saturation",
                "actions": ["scale_service", "notify_on_call"],
                "tags": ["latency", "traffic"],
            },
            {
                "kind": "release",
                "title": "{service} error spike after deploy",
                "description": "5xx rates climbed after a recent release while traffic remained stable.",
                "severity": IncidentSeverity.critical,
                "metrics": {"error_rate": 0.16},
                "root": "bad deployment",
                "actions": ["rollback_release", "open_ticket", "notify_on_call"],
                "tags": ["release", "5xx"],
            },
            {
                "kind": "false_positive",
                "title": "{service} alert storm with weak customer impact",
                "description": "Multiple alerts fired, but direct impact is unclear and evidence is incomplete.",
                "severity": IncidentSeverity.medium,
                "metrics": {"error_rate": 0.02},
                "root": "broader observability review",
                "actions": ["collect_diagnostics", "notify_on_call"],
                "tags": ["noisy", "uncertain"],
            },
            {
                "kind": "restart",
                "title": "{service} worker stall after maintenance",
                "description": "Workers appear stuck after a maintenance operation and a restart may be safe in non production.",
                "severity": IncidentSeverity.medium,
                "metrics": {"error_rate": 0.01},
                "root": "broader observability review",
                "actions": ["collect_diagnostics", "restart_service"],
                "tags": ["staging", "restart"],
            },
        ]

        cases: list[BenchmarkCase] = []
        for index in range(max(1, min(request.count, 12))):
            service = services[index % len(services)]
            template = templates[index % len(templates)]
            environment = environments[index % len(environments)]
            description = template["description"]
            tags = list(template["tags"])
            metrics = dict(template["metrics"])

            if request.include_noise and index % 2 == 0:
                description += " Alert payload also contains contradictory secondary metrics."
                tags.append("noise")
            if request.include_false_positives and template["kind"] == "false_positive":
                tags.append("false-positive")
            if request.include_incomplete_evidence and index % 3 == 0:
                description += " Only a partial log sample is available."
                tags.append("incomplete-evidence")

            cases.append(
                BenchmarkCase(
                    title=template["title"].format(service=service),
                    service=service,
                    environment=environment,
                    severity=template["severity"],
                    description=description,
                    source="synthetic",
                    metrics=metrics,
                    expected_root_cause=template["root"],
                    expected_actions=list(template["actions"]),
                    tags=tags + [request.difficulty],
                )
            )
        return cases
